// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('fourth test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('fourth test', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 1280, height: 680 })
    await driver.findElement(By.css("button:nth-child(1)")).click()
  })
})
