// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert')

describe('negativeS', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    // Set up Chrome options for headless mode
    const options = new chrome.Options();
    options.addArguments('--headless');
    options.addArguments('--no-sandbox');
    options.addArguments('--disable-dev-shm-usage');
    
    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(options)
      .build();
    vars = {}
  })
  afterEach(async function() {
    if (driver) {
      await driver.quit();
    }
  })
  it('negativeS', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect({ width: 945, height: 1020 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("-5")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("-3")
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})