name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Chrome and ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-dependencies: true

    - name: Get ChromeDriver Version
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "CHROMEDRIVER_VERSION=$CHROMEDRIVER_VERSION" >> $GITHUB_ENV

    - name: Download and Install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/${{ env.CHROMEDRIVER_VERSION }}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify Chrome and ChromeDriver Installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Install Dependencies
      run: npm install

    - name: Start Web Server
      run: python3 -m http.server 8000 &  
      working-directory: ./src

    - name: Run Selenium Tests
      run: npm test
      env:
        CHROME_BIN: /usr/bin/google-chrome
        SELENIUM_BROWSER: chrome